/* Edit game descriptions, media paths, store links, online play, and trailer paths here. */
const MASTERGAMER_GAMES = [
  {
    title: "Chicken Flapper: Haunted Forest",
    initials: "CF",
    accent: "#9b5cff",
    featured: true,
    platforms: ["iOS", "Android", "Web"],
    subtitle: "Have You Got What It Takes?",
    summary: "A fast-paced haunted forest arcade shooter packed with action and challenge.",
    description:
      "You are Chicken Flapper, battling your way through a haunted forest filled with terrifying creatures and powerful bosses.\n\nFace rabid bats, mummified birds, giant spiders, demons, scorpions, and more as you fight through increasingly difficult stages. Collect power-ups, defeat enemy hordes, and survive epic boss battles on your journey through the forest.\n\nA fast-paced arcade shooter packed with action, humour, and challenge.",
    media: {
      icon: "assets/games/chicken-flapper/chicken-flapper-icon.png",
      banner: "assets/games/chicken-flapper/chicken-flapper-banner.png",
      cover: "assets/games/chicken-flapper/chicken-flapper-screenshot1.png",
      screenshots: [
        "assets/games/chicken-flapper/chicken-flapper-screenshot1.png",
        "assets/games/chicken-flapper/chicken-flapper-screenshot2.png",
        "assets/games/chicken-flapper/chicken-flapper-screenshot3.png",
        "assets/games/chicken-flapper/chicken-flapper-screenshot4.png",
        "assets/games/chicken-flapper/chicken-flapper-screenshot5.png",
      ],
    },
    detailPage: "chicken-flapper.html",
    links: {
      appStore: null,
      googlePlay: null,
      playOnline: null,
      trailer: "assets/videos/chicken-flapper-trailer.mp4",
    },
  },
  {
    title: "Sevens",
    initials: "S7",
    accent: "#2bdcff",
    featured: true,
    platforms: ["iOS", "Android", "Web"],
    summary: "A strategic card game where every 7 starts the battle for the table.",
    description:
      "Mastergamer 7's brings the classic card game Sevens to life with modern visuals, intelligent AI opponents, and strategic gameplay.\n\nBuild each suit outward from the 7, manage your hand carefully, and outplay your opponents as you race to clear your cards and score points.\n\nEasy to learn. Difficult to master. Endless replayability.",
    features: [
      "Up to 5 AI opponents",
      "Adjustable difficulty levels",
      "Bonus turns with Aces and Kings",
      "Card hints and auto sorting",
      "Customisable game settings",
      "Local score tracking",
      "Fast and responsive gameplay",
    ],
    media: {
      icon: "assets/games/sevens/sevens-icon.png",
      banner: "assets/games/sevens/sevens-banner.png",
      cover: "assets/games/sevens/sevens-cover.png",
      screenshots: [
        "assets/games/sevens/sevens-screenshot1.png",
        "assets/games/sevens/sevens-screenshot2.png",
        "assets/games/sevens/sevens-screenshot3.png",
        "assets/games/sevens/sevens-screenshot4.png",
      ],
    },
    detailPage: "sevens.html",
    links: {
      appStore: "https://apps.apple.com/au/app/7s-sevens/id6777825705",
      googlePlay: "https://play.google.com/store/apps/details?id=com.base6a2233f69d637c03cc852909.app",
      playOnline: "coming-soon",
      trailer: "assets/videos/Sevens-trailer.mp4",
    },
  },
  {
    title: "TinyFall",
    initials: "TF",
    accent: "#ff4fd8",
    featured: true,
    platforms: ["iOS", "Android", "Web"],
    summary: "A colourful block-clearing puzzle game built for quick arcade fun.",
    description:
      "TinyFall is a colourful block-clearing puzzle game built for quick arcade fun.\n\nTap groups of matching blocks before the stack reaches the top. Every move matters--single blocks won't clear, so strategy and timing are key.\n\nChoose from Easy, Medium, Hard, or Pro modes and challenge yourself to achieve higher scores and faster clears.\n\nPop fast. Stack smart. Don't crack.",
    media: {
      icon: "assets/games/tinyfall/tinyfall-icon.png",
      banner: "assets/games/tinyfall/tinyfall-banner.png",
      cover: "assets/games/tinyfall/tinyfall-cover.png",
      screenshots: [
        "assets/games/tinyfall/tinyfall-screenshot1.png",
        "assets/games/tinyfall/tinyfall-screenshot2.png",
        "assets/games/tinyfall/tinyfall-screenshot3.png",
        "assets/games/tinyfall/tinyfall-screenshot4.png",
        "assets/games/tinyfall/tinyfall-screenshot5.png",
      ],
    },
    detailPage: "tinyfall.html",
    links: {
      appStore: "https://apps.apple.com/au/app/tinyfall/id6774491647",
      googlePlay: "https://play.google.com/store/apps/details?id=com.base6a041961dce7911d73a44175.app",
      playOnline: "coming-soon",
      trailer: "assets/videos/tinyfall-trailer.mp4",
    },
  },
  {
    title: "HumDing",
    initials: "HD",
    accent: "#7cff6b",
    featured: true,
    platforms: ["iOS", "Android", "Web"],
    summary: "A calm AI companion for thoughts, reminders, daily planning, and clarity.",
    description:
      "HumDing is a calm AI companion designed to help organise thoughts, ideas, reminders, and daily planning.\n\nCapture information through text or voice and let HumDing transform scattered thoughts into structured daily clarity.\n\nDesigned to reduce mental clutter and help you focus on what matters most.",
    features: [
      "Voice and text capture",
      "Daily summaries",
      "Thought organisation",
      "Story Cards",
      "Productivity support",
      "Personal planning",
    ],
    media: {
      icon: "assets/games/humding/humding-icon.png",
      banner: "assets/games/humding/humding-banner.png",
      cover: "assets/games/humding/humding-cover.png",
      screenshots: [
        "assets/games/humding/humding-screenshot1.png",
        "assets/games/humding/humding-screenshot2.png",
        "assets/games/humding/humding-screenshot3.png",
        "assets/games/humding/humding-screenshot4.png",
      ],
    },
    detailPage: "humding.html",
    links: {
      appStore: "https://apps.apple.com/au/app/humding/id6768580478",
      googlePlay: "https://play.google.com/store/apps/details?id=com.base69ffaa315dadf2c4ff53715b.app",
      playOnline: { url: "https://humding.ai/", label: "Login | Humding" },
      trailer: null,
    },
  },
  {
    title: "Chicken Blast",
    initials: "CB",
    accent: "#ffb84f",
    platforms: ["iOS", "Android", "Web"],
    summary: "Blast your chicken from a cannon and escape mischievous monkeys.",
    description:
      "Blast your chicken from a cannon and escape an army of mischievous monkeys in this fast-paced arcade adventure.\n\nCollect power-ups, dodge obstacles, and fly as far as possible while chasing high scores and leaderboard glory.\n\nSimple controls, colourful visuals, and endless gameplay make Chicken Blast easy to pick up and hard to put down.",
    media: {
      icon: "assets/games/chicken-blast/chicken-blast-icon.png",
      banner: "assets/games/chicken-blast/chicken-blast-banner.png",
      cover: "assets/games/chicken-blast/chicken-blast-cover.png",
      trailerThumbnail: "assets/games/chicken-blast/chicken-blast-video-thumbnail.png",
      video: "assets/games/chicken-blast/chicken-blast-video.mp4",
      screenshots: [
        "assets/games/chicken-blast/chicken-blast-screenshot1.png",
        "assets/games/chicken-blast/chicken-blast-screenshot2.png",
        "assets/games/chicken-blast/chicken-blast-screenshot3.png",
        "assets/games/chicken-blast/chicken-blast-screenshot4.png",
      ],
    },
    detailPage: "chicken-blast.html",
    links: {
      appStore: null,
      googlePlay: "https://play.google.com/store/apps/details?id=com.chkblast",
      playOnline: null,
      trailer: null,
    },
  },
  {
    title: "Pass Me",
    initials: "PM",
    accent: "#5878ff",
    platforms: ["iOS", "Android"],
    summary: "A fun multiplayer memory challenge for friends and family.",
    description:
      "Pass Me is a fun multiplayer memory challenge designed for family and friends.\n\nMemorise sequences, repeat them correctly, and pass the device to the next player. As rounds progress, patterns become increasingly difficult until only one memory champion remains.\n\nPlay solo or compete with up to four players across categories including colours, animals, faces, and objects.",
    features: [
      "Single-player memory training",
      "Multiplayer mode for up to four players",
      "Pattern recognition gameplay",
      "Categories including colours, faces, objects and animals",
      "Quick rounds for family and friends",
      "Easy to learn and fun to master",
    ],
    media: {
      icon: "assets/games/pass-me/pass-me-icon.png",
      banner: "assets/games/pass-me/pass-me-banner.png",
      cover: "assets/games/pass-me/pass-me-cover.png",
      screenshots: [
        "assets/games/pass-me/pass-me-screenshot1.png",
        "assets/games/pass-me/pass-me-screenshot2.png",
        "assets/games/pass-me/pass-me-screenshot3.png",
        "assets/games/pass-me/pass-me-screenshot4.png",
        "assets/games/pass-me/pass-me-screenshot5.png",
        "assets/games/pass-me/pass-me-screenshot6.png",
        "assets/games/pass-me/pass-me-screenshot7.png",
      ],
    },
    detailPage: "pass-me.html",
    links: {
      appStore: "https://apps.apple.com/au/app/pass-me/id6499293372",
      googlePlay: "https://play.google.com/store/apps/details?id=com.pass.me",
      playOnline: null,
      trailer: "assets/videos/pass-me-trailer.mp4",
    },
  },
  {
    title: "Chicken Splat",
    initials: "CS",
    accent: "#ff5a6f",
    platforms: ["iOS", "Android", "Web"],
    summary: "Guide chickens through 100 sheep-splatting arcade puzzle levels.",
    description:
      "Guide your chickens through 100 increasingly challenging levels as you attempt to eliminate troublesome sheep using strategy, timing, and unique character abilities.\n\nUnlock special chickens, discover power-ups, and prepare for the ultimate showdown against the Boss Sheep in Level 100.\n\nA quirky arcade puzzle experience packed with humour and challenge.",
    media: {
      icon: "assets/games/chicken-splat/chicken-splat-icon.png",
      banner: "assets/games/chicken-splat/chicken-splat-banner.png",
      cover: "assets/games/chicken-splat/chicken-splat-cover.png",
      screenshots: [
        "assets/games/chicken-splat/chicken-splat-screenshot1.png",
        "assets/games/chicken-splat/chicken-splat-screenshot2.png",
        "assets/games/chicken-splat/chicken-splat-screenshot3.png",
        "assets/games/chicken-splat/chicken-splat-screenshot4.png",
        "assets/games/chicken-splat/chicken-splat-screenshot5.png",
        "assets/games/chicken-splat/chicken-splat-screenshot6.png",
      ],
    },
    detailPage: "chicken-splat.html",
    links: {
      appStore: "https://apps.apple.com/au/app/pass-me/id6499293372",
      googlePlay: "https://play.google.com/store/apps/details?id=com.chicken.slap",
      playOnline: null,
      trailer: "assets/videos/chicken-splat-trailer.mp4",
    },
  },
  {
    title: "Lights Alive",
    initials: "LA",
    accent: "#32f5d2",
    platforms: ["iOS", "Android"],
    summary: "A fast-paced reflex game about timing, precision, and focus.",
    description:
      "Lights Alive is a fast-paced reflex game that tests your timing, precision, and concentration.\n\nWatch bouncing lights race across the screen and strike at exactly the right moment to score points and advance through increasingly difficult levels.\n\nChallenge the AI or compete head-to-head against a friend in fast and frantic battles.",
    media: {
      icon: "assets/games/lights-alive/lights-alive-icon.png",
      banner: "assets/games/lights-alive/lights-alive-banner.png",
      cover: "assets/games/lights-alive/lights-alive-cover.png",
      screenshots: [
        "assets/games/lights-alive/lights-alive-screenshot1.png",
        "assets/games/lights-alive/lights-alive-screenshot2.png",
        "assets/games/lights-alive/lights-alive-screenshot3.png",
        "assets/games/lights-alive/lights-alive-screenshot4.png",
        "assets/games/lights-alive/lights-alive-screenshot5.png",
      ],
    },
    detailPage: "lights-alive.html",
    links: {
      appStore: "https://apps.apple.com/au/app/lights-alive/id6452386754",
      googlePlay: "https://play.google.com/store/apps/details?id=com.lights.alive",
      playOnline: null,
      trailer: "assets/videos/lights-alive-trailer.mp4",
    },
  },
  {
    title: "Stoned",
    initials: "ST",
    accent: "#b78cff",
    platforms: ["iOS", "Android"],
    summary: "Match falling boxes fast before Jess makes another bad decision.",
    description:
      "Jess keeps making bad decisions--and it's your job to stop him.\n\nMatch falling boxes with your active box as the pace increases and mistakes become more costly.\n\nSimple to understand, surprisingly challenging to master, and packed with fast-paced arcade action.",
    media: {
      icon: "assets/games/stoned/stoned-icon.png",
      banner: "assets/games/stoned/stoned-banner.png",
      cover: "assets/games/stoned/stoned-cover.png",
      screenshots: [
        "assets/games/stoned/stoned-screenshot1.png",
        "assets/games/stoned/stoned-screenshot2.png",
        "assets/games/stoned/stoned-screenshot3.png",
        "assets/games/stoned/stoned-screenshot4.png",
        "assets/games/stoned/stoned-screenshot5.png",
      ],
    },
    detailPage: "stoned.html",
    links: {
      appStore: "https://apps.apple.com/au/app/stoned/id1591782319",
      googlePlay: "https://play.google.com/store/apps/details?id=com.re.stoned",
      playOnline: null,
      trailer: "assets/videos/stoned-trailer.mp4",
    },
  },
  {
    title: "Rock Paper Chicken",
    initials: "RPC",
    accent: "#f4f85a",
    category: "Classic Games / Archive Games",
    platforms: ["iOS", "Android", "Web"],
    summary: "A quirky twist on Rock, Paper, Scissors where chickens rule the championship.",
    description:
      "Take the classic Rock, Paper, Scissors formula and turn it into a quirky championship adventure.\n\nBattle your way through tournaments, challenge friends in local multiplayer, and compete to become the ultimate Rock Paper Chicken Champion.\n\nLuck, timing, and a little bit of madness await.",
    features: [
      "Classic Rock, Paper, Scissors gameplay with a chicken twist",
      "Single-player tournament mode",
      "Local two-player mode",
      "Fun cartoon characters",
      "Quick rounds and easy controls",
      "Family-friendly arcade humour",
    ],
    media: {
      icon: "assets/games/rock-paper-chicken/rock-paper-chicken-icon.png",
      banner: "assets/games/rock-paper-chicken/rock-paper-chicken-banner.png",
      cover: "assets/games/rock-paper-chicken/rock-paper-chicken-cover.png",
      screenshots: [
        "assets/games/rock-paper-chicken/rock-paper-chicken-screenshot1.png",
        "assets/games/rock-paper-chicken/rock-paper-chicken-screenshot2.png",
        "assets/games/rock-paper-chicken/rock-paper-chicken-screenshot3.png",
        "assets/games/rock-paper-chicken/rock-paper-chicken-screenshot4.png",
      ],
    },
    detailPage: "rock-paper-chicken.html",
    links: {
      appStore: "https://apps.apple.com/au/app/rock-paper-chicken/id6459266068",
      googlePlay: "https://play.google.com/store/apps/details?id=com.rpc.game",
      playOnline: null,
      trailer: "assets/videos/rock-paper-chicken-trailer.mp4",
    },
  },
  {
    title: "Cave Runner",
    subtitle: "Adventure Awaits Beneath the Surface",
    initials: "CR",
    accent: "#27a6ff",
    platforms: ["iOS", "Android", "Web"],
    summary: "A side-scrolling underground adventure in search of lost gold.",
    description:
      "Deep beneath the earth lies the legendary lost gold of Alcatraz, hidden within a maze of ancient caves, deadly traps, and forgotten treasures.\n\nAs the Cave Runner, you'll dodge hazards, leap across dangerous terrain, avoid collapsing caverns, and battle your way through increasingly challenging underground worlds in search of untold riches.\n\nEvery level brings new obstacles, greater dangers, and bigger rewards as you push deeper into the darkness.",
    features: [
      "Classic side-scrolling adventure gameplay",
      "Dangerous traps and hazards",
      "Hidden treasure and secrets",
      "Multiple cave environments",
      "Increasing difficulty and challenge",
      "Fast-paced arcade action",
    ],
    media: {
      icon: "assets/games/cave-runner/cave-runner-icon.png",
      banner: "assets/games/cave-runner/cave-runner-banner.png",
      cover: "assets/games/cave-runner/cave-runner-cover.png",
      screenshots: [
        "assets/games/cave-runner/cave-runner-screenshot1.png",
        "assets/games/cave-runner/cave-runner-screenshot2.png",
        "assets/games/cave-runner/cave-runner-screenshot3.png",
        "assets/games/cave-runner/cave-runner-screenshot4.png",
        "assets/games/cave-runner/cave-runner-screenshot5.png",
        "assets/games/cave-runner/cave-runner-screenshot6.png",
      ],
    },
    detailPage: "cave-runner.html",
    links: {
      appStore: "https://apps.apple.com/au/app/indiana-moans/id1601931715",
      googlePlay: "https://play.google.com/store/apps/details?id=com.cave.run",
      playOnline: null,
      trailer: "assets/videos/cave-runner-trailer.mp4",
    },
  },
  {
    title: "Flappy Christmas",
    initials: "FC",
    accent: "#5ed7ff",
    platforms: ["iOS", "Android", "Web"],
    summary: "A festive arcade adventure where Santa battles to save Christmas.",
    description:
      "The Ice Giant is trying to stop Christmas.\n\nGuide Santa through an enchanted forest filled with ghosts, ghouls, scorpions, and dangerous enemies. Collect snowballs, unlock power-ups, and battle your way to an epic showdown with the Ice Giant.\n\nA festive arcade adventure for players of all ages.",
    features: [
      "Festive arcade adventure gameplay",
      "Santa-themed flying action",
      "Snowball power-ups",
      "Enchanted forest enemies",
      "Boss battle against the Ice Giant",
      "Family-friendly Christmas fun",
    ],
    media: {
      icon: "assets/games/flappy-christmas/flappy-christmas-icon.png",
      banner: "assets/games/flappy-christmas/flappy-christmas-banner.png",
      cover: "assets/games/flappy-christmas/flappy-christmas-cover.png",
      screenshots: [
        "assets/games/flappy-christmas/flappy-christmas-screenshot1.png",
        "assets/games/flappy-christmas/flappy-christmas-screenshot2.png",
        "assets/games/flappy-christmas/flappy-christmas-screenshot3.png",
        "assets/games/flappy-christmas/flappy-christmas-screenshot4.png",
        "assets/games/flappy-christmas/flappy-christmas-screenshot5.png",
      ],
    },
    detailPage: "flappy-christmas.html",
    links: {
      appStore: null,
      googlePlay: "https://play.google.com/store/apps/details?id=com.flap.xmas",
      playOnline: null,
      trailer: null,
    },
  },
  {
    title: "Slap Santa",
    initials: "SS",
    accent: "#ff3864",
    platforms: ["iOS", "Android"],
    summary: "A festive tapping adventure packed with fast, funny holiday battles.",
    description:
      "Get ready for a festive tapping adventure in Slap Santa.\n\nJourney through a playful Christmas world filled with cheeky elves, magical fairies, spirited reindeer, and plenty of holiday mischief. Test your reflexes in fast, funny slap battles where every tap counts.\n\nWin battles, collect bonuses, boost your slapping power, and unlock new surprises as the world becomes brighter, wilder, and more festive.\n\nWith a final showdown against Santa himself, Slap Santa delivers light-hearted holiday fun for players of all ages.\n\nYour finger's journey to Santa starts now.",
    media: {
      icon: "assets/games/slap-santa/slap-santa-icon.png",
      banner: "assets/games/slap-santa/slap-santa-banner.png",
      cover: "assets/games/slap-santa/slap-santa-cover.png",
      screenshots: [
        "assets/games/slap-santa/slap-santa-screenshot1.png",
        "assets/games/slap-santa/slap-santa-screenshot2.png",
        "assets/games/slap-santa/slap-santa-screenshot3.png",
        "assets/games/slap-santa/slap-santa-screenshot4.png",
        "assets/games/slap-santa/slap-santa-screenshot5.png",
      ],
    },
    detailPage: "slap-santa.html",
    links: {
      appStore: "https://apps.apple.com/au/app/slap-santa/id1661397181",
      googlePlay: "https://play.google.com/store/apps/details?id=com.mb.slapsanta",
      playOnline: null,
      trailer: "assets/videos/slap-santa-trailer.mp4",
    },
  },
];
